apiVersion: apps/v1

kind: Deployment

metadata:

  name: webpage

  labels:

    app: webpage

spec:

  replicas: 3

  selector:

    matchLabels:

      app: webpage

  template:

    metadata:

      labels:

        app: webpage

    spec:

      containers:

      - name: htmlwebpage

        image: rpjadhav96/mywebpage:v1

        ports:

        - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: my-service
  labels:
    app: webpage
spec:
  selector:
    app: webpage
  type: NodePort
  ports:
  - nodePort: 
    port: 80
    targetPort: 80
